Changes done according to the comment
sohag16030/CMS-BACKEND pull request #15
Opened 2023-12-31 15:40 UTC by sohag16030

2024-01-01 09:42 UTC, suvro47 requested changes

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/Filter.java
> +public class Filter {
renamed it as geoFilterDto,also ceate a package named dto and put it there.

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/DistrictRepository.java
> +    List<District> findByFilter(@Param("districtId") Long districtId,
```suggestion
    List<District> search(@Param("districtId") Long districtId,
```
or

```suggestion
    List<District> filter(@Param("districtId") Long districtId,
```

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/DivisionRepository.java
> +    List<Division> findByFilter(@Param("divisionId") Long divisionId,
```suggestion
    List<Division> serach(@Param("divisionId") Long divisionId,
```

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/GeoController.java
> -            // TODO : throw EntityNotFoundException
keep this TODO comment

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/GeoController.java
> -            // TODO : throw EntityNotFoundException
keep this comment.

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/GeoController.java
> -            // TODO : throw EntityNotFoundException
keep this comment.

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/GeoService.java
> +            return divisionRepository.findAll();
why we need to handle this  manually ? isn't your method support this ?

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/GeoService.java
> +            return districtRepository.findAll();
why we need to handle this manually ? isn't your method support this ?

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/GeoService.java
> +            return upazilaRepository.findAll();
why we need to handle this manually ? isn't your method support this ?

2024-01-01 09:42 UTC, suvro47 commented on src/main/java/com/cms/example/cms/feature/geo/UpazilaRepository.java
> +            "(:districtId IS NULL OR u.district.districtId = :districtId)")
aei vabe nested na kore, first join kore rekhe dibi, then oi join use korbi

```suggestion
    @Query("SELECT u FROM Upazila u LEFT JOIN District d WHERE " +
            "(:upazilaId IS NULL OR u.upazilaId = :upazilaId) AND " +
            "(:name IS NULL OR u.name ILIKE %:name%) AND " +
            "(:nameLocal IS NULL OR u.nameLocal ILIKE %:nameLocal%) AND " +
            "(:active IS NULL OR u.active = :active) AND " +
            "(:districtId IS NULL OR d.districtId = :districtId)")
```

2024-01-01 14:31 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/Filter.java
> +public class Filter {
updated model name as  GeoFilterDto

2024-01-01 14:33 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/DistrictRepository.java
> +    List<District> findByFilter(@Param("districtId") Long districtId,
renamed the method as search instead of findByFilter

2024-01-01 14:33 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/GeoController.java
> -            // TODO : throw EntityNotFoundException
added the TODO

2024-01-01 14:41 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/GeoService.java
> +            return divisionRepository.findAll();
if(object==null){...}
code is changed according to this approach.

2024-01-01 14:41 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/GeoService.java
> +            return districtRepository.findAll();
if(object==null){...}
code is changed according to this approach.

2024-01-01 14:41 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/GeoService.java
> +            return upazilaRepository.findAll();
if(object==null){...}
code is changed according to this approach.

2024-01-01 14:43 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/GeoService.java
> +            return upazilaRepository.findAll();
if(object==null){...}
code is changed according to this approach.

2024-01-01 14:45 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/UpazilaRepository.java
> +            "(:districtId IS NULL OR u.district.districtId = :districtId)")
changed according to the comment.

2024-01-01 15:29 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/DivisionRepository.java
> +    List<Division> findByFilter(@Param("divisionId") Long divisionId,
renamed the method as search instead of findByFilter

2024-01-01 15:43 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/GeoController.java
> -            // TODO : throw EntityNotFoundException
added the TODO

2024-01-01 15:43 UTC, sohag16030 commented on src/main/java/com/cms/example/cms/feature/geo/GeoController.java
> -            // TODO : throw EntityNotFoundException
added the TODO

2024-01-03 05:44 UTC, suvro47 approved these changes

2024-01-03 05:44 UTC, merged